#! /bin/bash

#prints if user is logged in based on boolean 'isLoggedIn'
printStatus() {
	if $isLoggedIn; then
		echo "$argName is logged in"
	else
		echo "$argName is NOT logged in"
	fi
}

#"MAIN" of program
argName=$1 #set name variable to first argument

isLoggedIn=false #default value, bool stating if the user is logged in

#if the user did not enter an argument
if [ -z "$argName" ]; then
	echo "error: you must enter a user name."
	echo "example: ./isLoggedIn userName"
	exit 0
fi
#makes an array of all users logged into the system
declare -a userList=($(users))

#for loop iterates through each element of the user array
for itr in ${userList[@]}; do
	if [ "$argName" = "$itr" ]; then
		isLoggedIn=true
		break
	else
		isLoggedIn=false
	fi
done

#function call to print if the user is logged in or not
printStatus