#! /bin/sh

#prints if user is logged in based on boolean 'isLoggedIn'
printStatus() {
	if $isLoggedIn; then
		echo "$argName is logged in"
	else
		echo "$argName is NOT logged in"
	fi
}

#"MAIN" of program
argName=$1 #set name variable to first argument

isLoggedIn=false #default value, bool stating if the user is logged in

#if the user did not enter an argument
if [ -z "$argName" ]; then
	echo "error: you must enter a user name."
	echo "example: ./isLoggedIn userName"
	exit 0
fi

#who with the following flags parses the 
#usernames from the standard who command
currentUsers=$(who | cut -d' ' -f1) 

#parses currentUsers so currentUsers is now an array of users names
IFS=$'\n' 
set $currentUsers


#for loop iterates through each username pulled from the who command
for itr in $currentUsers; do
	if [ "$argName" = "$itr" ]; then
		isLoggedIn=true
		break
	else
		isLoggedIn=false
	fi
done

#function call to print if the user is logged in or not
printStatus
